dbt_aw:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: desafio-final-lh-449118  
      dataset: RAW
      threads: 4
      keyfile: /mnt/c/Users/ACER NITRO/Documents/GitHub/academy-dbt/desafio-final-lh-449118-6f025bf1fe9d.json
  target: dev
  