dbt_aw:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: desafio-final-lh-449118  
      dataset: RAW
      threads: 4
      keyfile: C:\Users\ACER NITRO\Documents\GitHub\academy-dbt\desafio-final-lh-449118-e15e6b41b26c.json
  target: dev
