version: 2 

sources:
  - name: RAW_sap_aw  # Nome exato do dataset no BigQuery
    database: desafio-final-lh-449118  # ID do seu projeto no BigQuery
    schema: RAW_sap_aw  # Nome do dataset no BigQuery
    tables:
      - name: address 
      - name: creditcard 
      - name: countryregion
      - name: customer
      - name: employee
      - name: salesperson 
      - name: person
      - name: product
      - name: productcategory
      - name: productsubcategory
      - name: salesorderdetail
      - name: salesorderheader
      - name: salesreason
      - name: stateprovince
      - name: salesterritory
      - name: store

    
    





